audit-log:
  log-save: all # способ сохранения логов: `console`, `file` или `all` (по умолчанию `all`)
  file-path: logs/spring-boot-application.log # путь к файлу для сохранения логов
  enable: true # включить или отключить логирование

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: deal
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:liquibase/db.changelog.yml
    enabled: true