audit-log:
  log-save: all # способ сохранения логов: `console`, `file` или `all` (по умолчанию `all`)
  file-path: logs/spring-boot-application.log # путь к файлу для сохранения логов
  enable: true # включить или отключить логирование
server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: deal
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  #      datasource:
#        username: postgres
#        password: postgres
#        url: jdbc:postgresql://localhost:5432/your_db
#        driver-class-name: org.postgresql.Driver
  topic:
    send-log: audit
  liquibase:
    change-log: classpath:liquibase/db.changelog.yml
    enabled: true
contractor:
  url: http://localhost:8080/contractors/
  cron: 0 * * * * ?

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855


